### ISSUE TITLE
update index.ts on file changes

### ISSUE THREAD

**Issue by neves** [Jordan-Eckowitz/indexify-vscode-extension#4]
If it's not possible to update on file changes, what about a shortcut ou right click menu to re-indexify?

**Comment by Jordan-Eckowitz** [comment]
Hi @neves, each time you right-click and re-select `Create Shallow Index` or `Create Deep Index` it should re-index everything.

Please let me know if its not working for you

**Comment by anishmansuri** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
vloddos, @Mrucznik, @Lwrless, @alexgzhou, @Uncommon-Dev, @ariaseta, @Caqlatufi, @zerovspace, @simonefrancia, @aph12123, @Pushkar1809, @jesusds603, @jeroenkurvers, @lisa0621, @laguiar, @dougbutner, @henry701, @0xGeegZ, @mdegraw, @demining, @rockdragon, @green-0-rabbit, @takumitx, @molagaz, @RobertoC27, @aroncds, @belgraderichard47, @nunorafaelrocha, @botsbuzz, @Ramonrune, @egeres, @krgko, @ondratra, @namnv09, @youngqqcn, @agarcialeon, @jaycausing, @zolotokrylin, @the25x8, @ada012, @AntonBenediuk, @0x-KChau, @willzhuang, @mayomi1, @creachang, @jimmyhong94, @hina90, @enes-t, @AceFire2014, @darkwater4213
