### ISSUE TITLE
Feature Request: It would be great if one could configure the type of index to be created.

### ISSUE THREAD

**Issue by AceTheWiz** [Jordan-Eckowitz/indexify-vscode-extension#6]
I have markdown documents which are organised in folders. Each folder typically needs an index file. In this case `index.md`
Each index entry is a list item in the form of a markdown link. `- [Filename](FilePathWithSpacesEscaped)`
for example
- [File 1 name](./subfolder/file1.md)
- [File 2 name](./File%202%20name.md)

If we could configure the 
1. file types (*.md in my case) to index
2. index file's name and extension (index.md)

See https://github.com/fjc0k/vscode-generate-index for ideas on a generic index builder.

Thanks

**Comment by Jordan-Eckowitz** [comment]
> 

Hi @AceTheWiz, I'm sorry but I'm not really following exactly what you want. 

Can you please write out an example of a folder containing the `.md` documents as well as an example of the index file format you'd expect out of it. 

Or, if you'd prefer, you can attach a `zip` file with the example.
